# Site settings
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://rustbeltriderscomposting.com" # the base hostname & protocol for your site
serverurl: https://rbr-backend.herokuapp.com
# Build settings
markdown: kramdown
host: 127.0.0.1
prose:
  media: images
  ignore:
    - .gitignore
    - _config.yml
    - /_layouts
    - /_sass
    - /geoms
    - /js
    - _includes
    - /bower_components
    - /css
    - /partials
    - bower.json
    - feed.xml
    - index.html
    - Readme.md
  metadata:
    _posts/faq:
      - name: "category"
        field:
          element: "hidden"
          value: "faq"
      - name: "layout"
        field:
          element: "hidden"
          value: "faq"
      - name: "title"
        field:
          element: "text"
          label: "Title"
      - name: "faqtype"
        field:
          element: "select"
          label: "FAQ Section"
          options:
            - name: General
              value: general
            - name: Why Compost?
              value: compost
            - name: Why a Cooperative?
              value: coop
