title: Rust Belt Riders Composting
description: An organic waste management solution creating wealth from waste. We Feed People, Not Landfills. 
phone: 440.781.1054
contactemail: info@rustbeltriders.com
address: 5401 Hamilton Ave, Cleveland, Ohio 44114
# Add social icons by specifying a key that matches with a fontawesome.io icon:
# http://fontawesome.io/icons/#brand
# and then the full URL to the profile
# i.e.:
# linkedin: http://linkedin.com/company/RustBeltRiders
social:
  twitter: https://twitter.com/RustBeltRiders
  facebook: https://www.facebook.com/RustBeltRidersCLE
  instagram: http://instagram.com/rustbeltriders
  linkedin: https://www.linkedin.com/company/rust-belt-riders
contact:
  success: Thanks for reaching out! We will get back to you shortly.
